namespace RogueLegacy.Enums;

public enum EnemyType
{
    None           = 0,
    BallAndChain   = 1,
    Blob           = 2,
    BouncySpike    = 3,
    Eagle          = 4,
    EarthWizard    = 5,
    Eyeball        = 6,
    Fairy          = 7,
    Fireball       = 8,
    FireWizard     = 9,
    Horse          = 10,
    IceWizard      = 11,
    Knight         = 12,
    Ninja          = 13,
    ShieldKnight   = 14,
    Skeleton       = 15,
    SwordKnight    = 16,
    Turret         = 17,
    Wall           = 18,
    Wolf           = 19,
    Zombie         = 20,
    SpikeTrap      = 21,
    Plant          = 22,
    Energon        = 23,
    Spark          = 24,
    SkeletonArcher = 25,
    Chicken        = 26,
    Platform       = 27,
    HomingTurret   = 28,
    LastBoss       = 29,
    Dummy          = 30,
    Starburst      = 31,
    Portrait       = 32,
    Mimic          = 33
}
