// 
// RogueLegacyArchipelago - SkillType.cs
// Last Modified 2021-12-27
// 
// This project is based on the modified disassembly of Rogue Legacy's engine, with permission to do so by its
// original creators. Therefore, former creators' copyright notice applies to the original disassembly.
// 
// Original Disassembled Source - © 2011-2015, Cellar Door Games Inc.
// Rogue Legacy™ is a trademark or registered trademark of Cellar Door Games Inc. All Rights Reserved.
// 

namespace RogueCastle.Structs
{
    public enum SkillType
    {
        Null,
        Filler,
        HealthUp,
        InvulnerabilityTimeUp,
        DeathDodge,
        AttackUp,
        DownStrikeUp,
        CritChanceUp,
        CritDamageUp,
        MagicDamageUp,
        ManaUp,
        ManaCostDown,
        Smithy,
        Enchanter,
        Architect,
        EquipUp,
        ArmorUp,
        GoldGainUp,
        PricesDown,
        PotionUp,
        RandomizeChildren,
        LichUnlock,
        BankerUnlock,
        SpellswordUnlock,
        NinjaUnlock,
        KnightUp,
        MageUp,
        AssassinUp,
        BankerUp,
        BarbarianUp,
        LichUp,
        NinjaUp,
        SpellSwordUp,
        SuperSecret,
        Divider,
        AttackSpeedUp,
        InvulnerabilityAttackUp,
        HealthUpFinal,
        EquipUpFinal,
        DamageUpFinal,
        ManaUpFinal,
        XpGainUp,
        GoldFlatBonus,
        ManaRegenUp,
        Run,
        Block,
        Cartographer,
        EnvDamageDown,
        GoldLossDown,
        VampireUp,
        StoutHeart,
        QuickOfBreath,
        BornToRun,
        OutTheGate,
        Perfectionist,
        Guru,
        IronLung,
        SwordMaster,
        Tank,
        Vampire,
        SecondChance,
        PeaceOfMind,
        CartographyNinja,
        StrongMan,
        Suicidalist,
        CritBarbarian,
        Magician,
        Keymaster,
        OneTimeOnly,
        CuttingOutEarly,
        Quaffer,
        SpellSword,
        Sorcerer,
        WellEndowed,
        TreasureHunter,
        MortarMaster,
        ExplosiveExpert,
        Icicle,
        Ender,
        ManorUpgrade,
        Traitorous,
    }
}
