namespace RogueCastle.Enums
{
    public enum ManorPieces
    {
        ObservatoryTelescope = 0,
        ObservatoryBase = 1,
        RightHighTower = 2,
        RightHighUpper = 3,
        RightHighBase = 4,
        RightExtension = 5,
        RightBigRoof = 6,
        RightBigUpper = 7,
        RightBigBase = 8,
        RightWingRoof = 9,
        RightWingBase = 10,
        RightWingWindow = 11,
        LeftExtension = 12,
        LeftFarRoof = 13,
        LeftFarBase = 14,
        LeftBigRoof = 15,
        LeftBigUpper2 = 16,
        LeftBigWindows = 17,
        LeftBigUpper1 = 18,
        LeftBigBase = 19,
        LeftWingRoof = 20,
        LeftWingBase = 21,
        LeftWingWindow = 22,
        GroundRoad = 24,
        MainRoof = 25,
        MainBase = 26,
        FrontWindowTop = 27,
        FrontWindowBottom = 28,
        LeftTree1 = 29,
        LeftTree2 = 30,
        RightTree = 31,
    }
}